const tooltips = {
    // Common work
    "Beggar": "日夜為幾個銅幣掙扎求存，每日感覺如臨死亡邊緣。",
    "Farmer": "耕田種植莊稼，收入不多，但誠實勞動。",
    "Fisherman": "捕撈各種魚類並賣出換取少量金錢，輕鬆但收入微薄的工作。",
    "Miner": "深入危險洞穴開採珍貴礦石，報酬與風險相比相當微薄。",
    "Blacksmith": "冶煉礦石並小心打造軍用武器，受人尊敬且收入尚可的平民工作。",
    "Merchant": "穿梭城鎮間，販賣優質貨物，收入不錯且較少體力勞動。",

    // Military
    "Squire": "在戰場上為騎士攜帶盾牌和劍，報酬極低但工作經驗寶貴。",
    "Footman": "以生命與敵軍交戰，勇敢且受尊敬的工作，但在大局中仍微不足道。",
    "Veteran footman": "比普通步兵更有經驗與用處，憑藉力量在戰場上消滅敵軍，報酬不錯。",
    "Centenary": "憑藉弓箭技巧被任命帶領一小隊弓箭手，遠距離伏擊敵人。",
    "Knight": "身披鋼甲，輕鬆斬殺敵兵，收入不錯且極受尊敬的工作。",
    "Veteran Knight": "運用無與倫比的戰鬥能力，輕鬆屠戮敵人，多數軍中步兵難以獲得如此高薪工作。",
    "Holy Knight": "以非凡技藝一舉殲滅敵軍，揮舞魔法灌注之劍，戰場上令人畏懼的單位，報酬極高。",
    "Lieutenant General": "令列國畏懼，瞬間殲滅整支軍隊，每世紀僅一位聖騎士能獲得此崇高稱號。",

    // The Arcane Association
    "Student": "學習魔力理論與練習基礎魔法，微薄薪酬用以支付生活費，但成為法師的必經階段。",
    "Apprentice Mage": "在資深法師指導下，對敵施展基礎魔法，慷慨報酬用以支付生活費。",
    "Adept Mage": "通過施展中級魔法扭轉戰局，並指導其他學徒，報酬極高。",
    "Master Wizard": "運用高級魔法摧毀整支敵軍，只有少數法師能達到此角色，報酬極高。",
    "Archmage": "擁有無與倫比的天賦，隨心施展不可思議的魔法，據說可將帝國從地圖上抹去。",
    "Chronomancer": "專精於操控時間能量，以超自然預言與異世界專長改變時間流動。",
    "Chairman": "管理奧術協會並研究真正不朽的概念，每日獲得巨額報酬。",
    "Imperator": "擁有無限力量，無人能敵，以鐵腕統治奧術協會，所有人必須服從你的命令。",

    // The Void
    "Corrupted": "被虛空腐化，逐漸變成無自由意志的奴隸，永遠為虛空服務……你能抵抗，還是永遠被吞噬？",
    "Void Slave": "每日愈發屈服於虛空，你能再堅持人性片刻，還是讓虛空吞噬你？",
    "Void Fiend": "你變成一個好奇卻腐朽的生物，吸取周圍一切生命。",
    "Abyss Anomaly": "尖叫著誕生，你成為超越未知虛無的化身。",
    "Void Wraith": "受詛咒的靈魂……你成為昔日自我的陰影，徘徊於不同領域，被虛空吞噬……你能找到安寧嗎？",
    "Void Reaver": "少數能穿梭世界之間的生物，擁有生成吞噬一切生命的虛空能量場的能力。",
    "Void Lord": "長久凝視虛空黑暗之心，你成為最強大且令人畏懼的存在，所有低等虛空生物聽你指揮。",
    "Abyss God": "虛空的創造者，一片廣闊的黑暗與虛無，其存在本身違背所有邏輯，無人能逃脫你的掌控。",

    // Galactic Council
    "Eternal Wanderer": "被未知存在賦予力量，你四處漫遊，尋找受人敬畏與恐懼之地的答案。",
    "Nova": "極其強大的存在，擁有驚人念力與重組物質和能量分子結構的能力，甚至達至宇宙規模。",
    "Sigma Proioxis": "近乎全能的宇宙實體，擁有廣泛的物質與能量操控能力，推動宇宙本身的界限。",
    "Acallaris": "早於宇宙誕生的原初存在，參與生命創造，超越凡人理解，存在於宇宙最古老物種的神話中。",
    "One Above All": "一切的創造者。",

    // Metaverse Guards
    "Snow Crash": "雪崩，1992年",
    "Player One": "挑戰者一號，2011年",
    "Lost in the dark": "他們知道只有彼此相伴才能前行。他們發誓永遠在一起，賺很多錢，搬到更好的地方，過幸福生活。",
    "Omega": "ω",

    // Fundamentals
    "Concentration": "通過練習高強度專注活動，提升學習速度。",
    "Productivity": "學會減少工作拖延，每日獲得更多工作經驗。",
    "Bargaining": "研究交易技巧與說服技能，降低各類開支。",
    "Meditation": "讓內心充滿和平與寧靜，從內心汲取更大幸福。",

    // Combat
    "Strength": "通過嚴苛訓練增強身體與力量，軍中強者獲得更高報酬。",
    "Battle Tactics": "制定與修訂戰鬥策略，提升軍中經驗獲取。",
    "Muscle Memory": "通過習慣與重複強化神經，提升全身力量增益。",

    // Magic
    "Mana Control": "強化全身魔力通道，助你成為更強大的魔法使用者。",
    "Life Essence": "通過魔法延長壽命，但這真的是你追求的不朽嗎……？",
    "Time Warping": "運用禁忌技巧扭曲空間與時間，加速學習過程。",
    "Astral Body": "利用以太能量大幅延長壽命，超越理解。",
    "Temporal Dimension": "創造屬於你的口袋維度，數世紀僅為數秒。",
    "All Seeing Eye": "作為奧術協會最高階，所有資金直接歸於你。",
    "Brainwashing": "操控人類思想與行為的技巧，違背其意願。",

    // Dark Magic - Evil Required
    "Dark Influence": "被邪惡賦予強大力量，讓你輕鬆掌握與吸收任何工作或技能。",
    "Evil Control": "馴服內心肆虐增長的邪惡，提升重生間的邪惡增益。",
    "Intimidation": "學會散發惡魔氣息，令其他商人極度恐懼，迫使他們給予大幅折扣。",
    "Demon Training": "人類身體太脆弱無法承受邪惡，通過禁忌方法訓練，逐漸化為惡魔，快速吸收知識。",
    "Blood Meditation": "通過犧牲其他生物，培養內心邪惡，大幅提升邪惡增益。",
    "Demon's Wealth": "通過暗黑魔法，倍增你從工作中獲得的貨幣物質。",
    "Dark Knowledge": "長久封印的禁忌文獻，你用其謀取個人利益。",
    "Void Influence": "結合虛空與邪惡的力量，賦予你無限潛能。",
    "Time Loop": "當你能「告訴時間該做什麼」時，便達至掌控。",
    "Evil Incarnate": "你成為了自己曾誓言消滅的東西。",

    // Void Manipulation
    "Absolute Wish": "實現任何無限願望的力量，毫無限制。",
    "Void Amplification": "你向虛空屈服，使其更容易控制你。",
    "Mind Release": "在類似催眠的狀態下，虛空放大你的思想、感知、記憶、情感與人格。",
    "Ceaseless Abyss": "永無止境的折磨，你發誓永遠為虛空服務。",
    "Void Symbiosis": "與虛空的共生關係，助你與虛空合為一體。",
    "Void Embodiment": "若你長久凝視深淵，深淵亦凝視你。",
    "Abyss Manipulation": "讓你在虛空中塑造屬於自己的現實。",

    // Celestial Powers
    "Cosmic Longevity": "你見證了一切，從最初到最終。",
    "Cosmic Recollection": "能同時存在於多個平行時間線，操控你的平行自我，影響他們的人生。",
    "Essence Collector": "利用多元宇宙的無限潛能，收集其資源。",
    "Galactic Command": "絕對的權力帶來絕對的腐化。",

    // Almightiness
    "Yin Yang": "宇宙初創時從混沌中誕生，相信其平衡邪惡與善良。",
    "Parallel Universe": "獨立存在的平面，與自身共存，助你恢復遺忘的力量碎片。",
    "Higher Dimensions": "擁有部分改變物理定律與超越低維空間的力量，你的存續永無止境。",
    "Epiphany": "你與萬物合為一體。",

    // Darkness
    "Dark Prince": "因能接觸宇宙所有圖書館，你的智力以驚人速度增長。",
    "Dark Ruler": "統治宇宙讓你從下屬收集更多暗物質。",
    "Immortal Ruler": "你只有一個目標：統治宇宙直至永遠。",
    "Dark Magician": "對下屬施展禁忌魔法，榨取他們最後一滴精華。",
    "Universal Ruler": "以鐵腕統治，無人敢挑戰你的權威。",
    "Blinded By Darkness": "被黑暗蒙蔽，你無法控制自己，開始摧毀一切以平靜心緒。",

    // Properties
    "Homeless": "睡在不舒適、骯髒的街道上，每晚幾乎凍死，情況不能更糟。",
    "Tent": "由幾根脆弱木棒支撐的破布薄片，居住條件惡劣，但至少有個遮蓋。",
    "Wooden Hut": "由粗糙木材與骯髒乾草用馬糞黏合而成，比帳篷堅固，但氣味難聞。",
    "Cottage": "以木框架與茅草屋頂構築，提供合理居住條件，價格公道。",
    "House": "由石磚與堅固木材建成，包含數個房間，雖昂貴但舒適。",
    "Large House": "比普通房子大得多，擁有更多房間與多層樓，空間寬敞但價格高昂。",
    "Small Palace": "以銀等貴金屬裝飾的奢華建築，維持奢華生活開支極高。",
    "Grand Palace": "完全由金銀構成的宏偉住所，提供極致奢華舒適的居住條件，價格極高。",
    "Town Ruler": "你統治自己的小鎮，擁有多个產業。",
    "City Ruler": "作為最高官員，你管理與監督一切，收入驚人但開支亦然。",
    "Nation Ruler": "你統治整個國家，財富或許腐化，但一切皆屬於你。",
    "Pocket Dimension": "可隨意召喚的專屬維度，發生在那裡的事僅限於那裡。",
    "Void Realm": "不知何時何地形成的虛空領域，包含獨特的維度元素，現全由你支配。",
    "Void Universe": "早於我們宇宙的虛空，擁有無限空間供你存放物品，前提是你願意屈服。",
    "Astral Realm": "在人格與自我之下，是我們深層性格的根源，包含心靈感官、深層思想與情感、符號與內在現實。",
    "Galactic Throne": "你坐在寶座上，俯瞰存在本身。",
    "Spaceship": "你的個人宇宙居所，能以99.99%光速穿梭宇宙任何地方。",
    "Planet": "專為你與家人居住的行星。",
    "Ringworld": "擁有木星質量、表面積比地球大數百萬倍的構造，可容納數萬億人類與其他物種，包括外星物種。維持結構穩定與內部宜居的開支極高，但巨大生活空間值得。",
    "Stellar Neighborhood": "一個完全殖民的星系網絡，跨越數十光年，供你探索與稱為家。",
    "Galaxy": "你統治一個與銀河系同等大小的星系，包含數十億行星，分為數千個由你控制的州。權力驚人，責任亦然。",
    "Supercluster": "包含數十個超星系團與數千個星系，跨越數億光年的星系群，由你掌控。",
    "Galaxy Filament": "宇宙中已知的最大結構之一，包含數十個超星系團與數百萬星系。",
    "Observable Universe": "你成功了！你終於統治整個宇宙……還是沒有？",
    "Multiverse": "宇宙對你來說太小了？！",
    "Quantum World": "你試圖尋找仍不受你控制的地方，但一切徒勞。",
    "Boötes Void": "偉大的虛無",

    // Misc
    "Book": "記錄你的思想與發現的地方，讓你學習更快。",
    "Dumbbells": "用於艱苦鍛鍊的重型工具，助你更快增強力量。",
    "Personal Squire": "協助你完成日常活動，讓你有更多時間專注工作。",
    "Steel Longsword": "精良的劍刃，助你在戰鬥中更快擊殺敵人，獲得更多經驗。",
    "Butler": "保持居所整潔，每日準備三餐美味，讓你心情愉快無壓力。",
    "Sapphire Charm": "鑲嵌稀有藍寶石的護符，激活更多魔力通道，助你更輕鬆學習魔法。",
    "Study Desk": "專用研究區域，提供精良文具與設備，促進研究進展。",
    "Library": "儲存大量書籍，包含從基本生活技能到複雜魔法咒語的豐富資訊。",
    "Observatory": "用於觀察陸地、海洋與天文事件。",
    "Mind's Eye": "讓你看見記憶、回想圖像，甚至看到新圖片與想法。",
    "Void Necklace": "助你塑造與操控虛空物質，甚至將其轉化與重塑為你想要的任何東西。",
    "Void Armor": "生成成為你身體一部分的天然護甲，抵禦攻擊、傷害或疼痛。",
    "Void Blade": "由虛空塵埃與暗物質鍛造的劍刃，可斬斷維度障礙，是每位虛空掠奪者的首選武器。",
    "Void Orb": "當此球接觸非虛空實體時，會利用虛空領域的力量瞬間分解它們。",
    "Void Dust": "最純粹的虛空創造物質，一茶匙重量相當於一顆小行星。",
    "Celestial Robe": "每位天皇最重要的裝備，無限力量的來源。",
    "Universe Fragment": "自宇宙誕生之時，可創造更多小型宇宙。",
    "Multiverse Fragment": "早於我們宇宙誕生，無形且散發無限能量的奇異物體。",
    "Stairway to heaven": "通往全能者的階梯。",
    "Highway to hell": "魔鬼邀請你前往他的恐怖宮殿。",
    "Tesseract": "來自更高維度世界的物體。",
    "Desintegration": "你為何需要它？",
    "Custom Galaxy": "你知道口袋維度，對吧？",
    "Hypersphere": "你獲得無限力量……啊，你已經全能了……",

    // Essence Milestones
    "Magic Eye": "你護符中的眼睛開始發光。",
    "Almighty Eye": "你護符中的眼睛如星辰般閃耀。",
    "Deal with the Devil": "你與魔鬼達成交易。",
    "Transcendent Master": "你已掌握超越。",
    "Eternal Time": "時間現在還有意義嗎？",
    "Hell Portal": "你開啟了通往地獄的門戶。",
    "Inferno": "你到達地獄的最後一層，接下來是什麼？",
    "God's Blessings": "神祝福你！",
    "Faint Hope": "或許還有希望？",
    "New Beginning": "嘗試將「至高無上」升至2000級",

    // Heroic Milestones
    "Rise of Great Heroes": "每項活躍的偉大工作或技能將略微增加精華增益。",
    "Lazy Heroes": "總英雄經驗倍數為5e20",
    "Dirty Heroes": "總英雄經驗倍數為5e35",
    "Angry Heroes": "總英雄經驗倍數為5e50",
    "Tired Heroes": "總英雄經驗倍數為5e65",
    "Scared Heroes": "總英雄經驗倍數為5e80",
    "Good Heroes": "總英雄經驗倍數為5e95",
    "Funny Heroes": "總英雄經驗倍數為5e120",
    "Beautiful Heroes": "總英雄經驗倍數為5e170",
    "Awesome Heroes": "總英雄經驗倍數為5e180",
    "Furious Heroes": "總英雄經驗倍數為5e198",
    "Superb Heroes": "總英雄經驗倍數為5e201",
    "A new beginning": "解鎖為暗物質重置的能力",

    // Dark Milestones
    "Mind Control": "控制魔鬼，讓他每秒給你更多邪惡。",
    "Galactic Emperor": "銀河理事會指揮官授予你自動從附近行星收集精華的特權。",
    "Dark Matter Harvester": "收割宇宙，從中提取更多暗物質。",
    "A Dark Era": "開啟暗物質的新時代。",
    "Dark Orbiter": "利用一些巫術，你可大幅提升暗球生成器的效能。",
    "Dark Matter Mining": "從你造訪的每顆行星開採大量暗物質。",
    "The new gold": "由於廣泛採用，精華或成為新黃金。",
    "The Devil inside you": "與魔鬼的陰暗交易為你帶來巨大邪惡加成。",
    "Strange Magic": "一位怪巫師提供你幾個可能有用的秘密魔法。",
    "Life is valueable": "時間有限……即使作為宇宙統治者。",
    "Speed speed speed": "你能用巨量暗物質影響宇宙速度。",
    "Dark Matter Millionaire": "此秘密魔法助你達成成為首位暗物質百萬富翁的目標。",
    "The new Dark Matter": "你的護符撕裂所有多元宇宙的空間與時間，歡迎來到元宇宙。",

    "Strong Hope": "又一個微弱希望加成？！",
    "Ruler of the Metaverse": "現在你開始用傳送門思考。",
    "A New Hope": "不再是那些微弱希望的廢話！！！",
    "Time is a flat circle": "這是一個無解的世界。有人曾告訴我，時間是個平圓。我們做過或將做的一切，都將一再重複。",
    "The End is near": "我們不試圖永遠活下去。",
    "The End": "總有終結。"
}