const keywords = {
    // Common work
    "Beggar": "乞丐",
    "Farmer": "農夫",
    "Fisherman": "漁夫",
    "Miner": "礦工",
    "Blacksmith": "鐵匠",
    "Merchant": "商人",

    // Military
    "Squire": "侍從",
    "Footman": "步兵",
    "Veteran footman": "資深步兵",
    "Centenary": "百夫長",
    "Knight": "騎士",
    "Veteran Knight": "資深騎士",
    "Holy Knight": "聖騎士",
    "Lieutenant General": "中將",

    // The Arcane Association
    "Student": "學生",
    "Apprentice Mage": "學徒法師",
    "Adept Mage": "熟練法師",
    "Master Wizard": "大魔法師",
    "Archmage": "大魔導師",
    "Chronomancer": "時空法師",
    "Chairman": "主席",
    "Imperator": "皇帝",

    // The Void
    "Corrupted": "腐化者",
    "Void Slave": "虛空奴隸",
    "Void Fiend": "虛空惡魔",
    "Abyss Anomaly": "深淵異象",
    "Void Wraith": "虛空幽魂",
    "Void Reaver": "虛空掠奪者",
    "Void Lord": "虛空領主",
    "Abyss God": "深淵之神",

    // Galactic Council
    "Eternal Wanderer": "永恆漫遊者",
    "Nova": "新星",
    "Sigma Proioxis": "西格瑪·普羅伊克斯",
    "Acallaris": "阿卡拉里斯",
    "One Above All": "至高無上",

    // Metaverse Guards
    "Snow Crash": "雪崩",
    "Player One": "玩家一號",
    "Lost in the dark": "迷失黑暗",
    "Omega": "歐米伽",

    // Fundamentals
    "Concentration": "專注",
    "Productivity": "生產力",
    "Bargaining": "議價",
    "Meditation": "冥想",

    // Combat
    "Strength": "力量",
    "Battle Tactics": "戰術",
    "Muscle Memory": "肌肉記憶",

    // Magic
    "Mana Control": "魔力控制",
    "Life Essence": "生命精華",
    "Time Warping": "時間扭曲",
    "Astral Body": "星體",
    "Temporal Dimension": "時空維度",
    "All Seeing Eye": "全視之眼",
    "Brainwashing": "洗腦",

    // Dark Magic - Evil Required
    "Dark Influence": "黑暗影響",
    "Evil Control": "邪惡控制",
    "Intimidation": "恐嚇",
    "Demon Training": "惡魔訓練",
    "Blood Meditation": "血之冥想",
    "Demon's Wealth": "惡魔財富",
    "Dark Knowledge": "黑暗知識",
    "Void Influence": "虛空影響",
    "Time Loop": "時間循環",
    "Evil Incarnate": "邪惡化身",

    // Void Manipulation
    "Absolute Wish": "絕對願望",
    "Void Amplification": "虛空增幅",
    "Mind Release": "心靈釋放",
    "Ceaseless Abyss": "無盡深淵",
    "Void Symbiosis": "虛空共生",
    "Void Embodiment": "虛空化身",
    "Abyss Manipulation": "深淵操控",

    // Celestial Powers
    "Cosmic Longevity": "宇宙長壽",
    "Cosmic Recollection": "宇宙回憶",
    "Essence Collector": "精華收集者",
    "Galactic Command": "銀河指揮",

    // Almightiness
    "Yin Yang": "陰陽",
    "Parallel Universe": "平行宇宙",
    "Higher Dimensions": "高等維度",
    "Epiphany": "頓悟",

    // Darkness
    "Dark Prince": "黑暗王子",
    "Dark Ruler": "黑暗統治者",
    "Immortal Ruler": "不朽統治者",
    "Dark Magician": "黑暗魔法師",
    "Universal Ruler": "宇宙統治者",
    "Blinded By Darkness": "被黑暗蒙蔽",

    // Properties
    "Homeless": "無家可歸",
    "Tent": "帳篷",
    "Wooden Hut": "木屋",
    "Cottage": "村舍",
    "House": "房屋",
    "Large House": "大宅",
    "Small Palace": "小宮殿",
    "Grand Palace": "大宮殿",
    "Town Ruler": "鎮長",
    "City Ruler": "城主",
    "Nation Ruler": "國王",
    "Pocket Dimension": "口袋維度",
    "Void Realm": "虛空領域",
    "Void Universe": "虛空宇宙",
    "Astral Realm": "星界",
    "Galactic Throne": "銀河寶座",
    "Spaceship": "太空船",
    "Planet": "行星",
    "Ringworld": "環形世界",
    "Stellar Neighborhood": "星際鄰里",
    "Galaxy": "星系",
    "Supercluster": "超星系團",
    "Galaxy Filament": "星系纖維",
    "Observable Universe": "可觀測宇宙",
    "Multiverse": "多元宇宙",
    "Quantum World": "量子世界",
    "Boötes Void": "布特斯虛空",

    // Misc
    "Book": "書籍",
    "Dumbbells": "啞鈴",
    "Personal Squire": "私人侍從",
    "Steel Longsword": "鋼製長劍",
    "Butler": "管家",
    "Sapphire Charm": "藍寶石護符",
    "Study Desk": "書桌",
    "Library": "圖書館",
    "Observatory": "天文台",
    "Mind's Eye": "心靈之眼",
    "Void Necklace": "虛空項鍊",
    "Void Armor": "虛空護甲",
    "Void Blade": "虛空之刃",
    "Void Orb": "虛空寶珠",
    "Void Dust": "虛空塵埃",
    "Cel()}estial Robe": "天皇長袍",
    "Universe Fragment": "宇宙碎片",
    "Multiverse Fragment": "多元宇宙碎片",
    "Stairway to heaven": "天堂階梯",
    "Highway to hell": "地獄高速公路",
    "Tesseract": "超立方體",
    "Desintegration": "分解",
    "Custom Galaxy": "自訂星系",
    "Hypersphere": "超球體",

    // Essence Milestones
    "Magic Eye": "魔法之眼",
    "Almighty Eye": "全能之眼",
    "Deal with the Devil": "與魔鬼交易",
    "Transcendent Master": "超凡大師",
    "Eternal Time": "永恆時間",
    "Hell Portal": "地獄入口",
    "Inferno": "烈焰地獄",
    "God's Blessings": "神的祝福",
    "Faint Hope": "微弱希望",
    "New Beginning": "新開始",

    // Heroic Milestones
    "Rise of Great Heroes": "偉大英雄崛起",
    "Lazy Heroes": "懶惰英雄",
    "Dirty Heroes": "骯髒英雄",
    "Angry Heroes": "憤怒英雄",
    "Tired Heroes": "疲憊英雄",
    "Scared Heroes": "恐懼英雄",
    "Good Heroes": "善良英雄",
    "Funny Heroes": "滑稽英雄",
    "Beautiful Heroes": "美麗英雄",
    "Awesome Heroes": "驚人英雄",
    "Furious Heroes": "狂怒英雄",
    "Superb Heroes": "卓越英雄",
    "A new beginning": "全新開始",

    // Dark Milestones
    "Mind Control": "精神控制",
    "Galactic Emperor": "銀河皇帝",
    "Dark Matter Harvester": "暗物質收割者",
    "A Dark Era": "黑暗時代",
    "Dark Orbiter": "暗軌道者",
    "Dark Matter Mining": "暗物質開採",
    "The new gold": "新黃金",
    "The Devil inside you": "內心的魔鬼",
    "Strange Magic": "怪奇魔法",
    "Life is valueable": "生命珍貴",
    "Speed speed speed": "速度至上",
    "Dark Matter Millionaire": "暗物質百萬富翁",
    "The new Dark Matter": "新暗物質",

    "Strong Hope": "強烈希望",
    "Ruler of the Metaverse": "元宇宙統治者",
    "A New Hope": "新希望",
    "Time is a flat circle": "時間是平圓",
    "The End is near": "終結將近",
    "The End": "終結",

    "Common work": "普通工作",
    "Military": "軍事",
    "The Arcane Association": "奧術協會",
    "The Void": "虛空",
    "Galactic Council": "銀河議會",
    "Metaverse Guards": "元宇宙守護者",

    "Fundamentals": "基礎",
    "Combat": "戰鬥",
    "Magic": "魔法",
    "Dark Magic": "黑暗魔法",
    "Void Manipulation": "虛空操控",
    "Celestial Powers": "天體力量",
    "Almightiness": "全能",
    "Darkness": "黑暗",

    "Properties": "資產",
    "Misc": "雜項",

    "Effect": "效果",
    "Income": "收入",

    "Happiness": "幸福感",
}